services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USER}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
    ports:
      - "5430:5432"