INSERT INTO roles (name) VALUES
    ('USER'),
    ('PUP'),
    ('OD'),
    ('ADMIN');

INSERT INTO status (name, description) VALUES
    ('ACTIVE', ''),
    ('INACTIVE', ''),
    ('PENDING', ''),
    ('CANCELED', ''),
    ('COMPLETED', ''),
    ('ARCHIVED', ''),
    ('CREATED', ''),
    ('DELETED', ''),
    ('REJECTED', ''),
    ('APPROVED', ''),
    ('EXPIRED', ''),
    ('SUSPENDED', ''),
    ('FAILED', ''),
    ('PROCESSING', ''),
    ('QUEUED', ''),
    ('IN_PROGRESS', ''),
    ('ON_HOLD', ''),
    ('RESOLVED', ''),
    ('ESCALATED', ''),
    ('CLOSED', ''),
    ('OPEN', ''),
    ('NEW', ''),
    ('ASSIGNED', ''),
    ('UNASSIGNED', '');